default:
  image: 
    name: public.ecr.aws/docker/library/alpine:edge
  tags: 
    - test

variables:
  KMS_KEY_ID: ""
  ENVIRONMENT: ""

stages:
  - initialization
  - authorization
  - build
  - test
  - deploy
