default:
  image: 
    name: public.ecr.aws/docker/library/alpine:edge
  tags: 
    - test

variables:
  KMS_KEY_ID: ""
  ENVIRONMENT: ""
  NODE_IMAGE: "node:14"

stages:
  - initialization
  - authorization
  - build
  - test
  - deploy

before_script:
  - npm install  # Install dependencies before running tests

test: 
  stage: test
  image: $NODE_IMAGE
  scripts: 
    - npm test
